### PR TITLE
fix(core): fix subPackage cannot match the second-level dir

### PR DESCRIPTION
**Pull request by Skiyee**
fixes: #152 

## Summary by CodeRabbit

- **New Features**
	- Introduced new About and Home pages for both 'sub-activity' and 'sub-main' sections in the playground package, enhancing navigation and user interaction.

- **Bug Fixes**
	- Improved the routing calculation in PageContext to ensure accurate path generation based on the project structure, enhancing reliability.

- **Tests**
	- Added new test case to address and fix the sub-package matching issue for second-level directories, ensuring robust functionality.

### CODE REVIEW

**Comment by ModyQyW** [comment]
LGTM

**Comment by Shigukj** [comment]
正是我需要的

**Comment by wukongkong** [comment]
感谢~

**Comment by ModyQyW** [comment]
如果没有进一步需要修改的反馈，我计划在明天合并并发布该 PR

**Comment by ModyQyW** [comment]
Thank you!

**Comment by DuduStyle** [comment]
新的配置规则是什么？没看明白？
subPackages: ['src/sub-pages', 'src/sub-pages/report'],
此类配置形式，sub-pages分包的内容里依然包含report路由

**Comment by Skiyee** [comment]
该配置是指定某个文件夹让其成为分包的

如果把 `src/sub-pages` 当成分包，那么此时在该文件夹下的 `文件(无论在哪个层级)` 都会被当作 “页面”

> PS: 建议不要在让分包嵌套分包

**Pull request merged**
